flashcards/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create_flashcard/', views.create_flashcard, name="create_flashcard"),
    path('delete_flashcard/<int:id>', views.delete_flashcard, name="delete_flashcard"),
    path('create_challenge/', views.create_challenge, name="create_challenge"),
    path('index_challenges/', views.index_challenges, name="index_challenges"),
    path('challenge/<int:id>/', views.challenge, name='challenge'),
    path('answer_flashcard/<int:id>/', views.answer_flashcard, name='answer_flashcard'),
    path('report/<int:id>/', views.report, name='report')
]

flex_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('flashcards/', include('flashcards.urls')),
    path('summaries/', include('summaries.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

flashcards/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__ (self):
        return self.name
    
class Flashcard(models.Model):
    DIFFICULTY_CHOICES = (('D', 'Difícil'), ('M', 'Médio'), ('F', 'Fácil'))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    question = models.CharField(max_length=100)
    answer = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY_CHOICES)

    def __str__(self):
        return self.question
    
    @property
    def css_difficulty(self):
        if self.difficulty == 'F':
            return 'flashcard-easy'
        elif self.difficulty == 'M':
            return 'flashcard-medium'
        elif self.difficulty == 'D':
            return 'flashcard-difficult'
    
class FlashcardChallenge(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.DO_NOTHING)
    answered = models.BooleanField(default=False)
    flashcard_success = models.BooleanField(default=False)

    def __str__(self):
        return self.flashcard.question

class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    category = models.ManyToManyField(Category)
    number_questions = models.IntegerField()
    difficulty = models.CharField(max_length=1, choices=Flashcard.DIFFICULTY_CHOICES)
    flashcards = models.ManyToManyField(FlashcardChallenge)

    def __str__(self):
        return self.title

flashcards/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from . models import Category, Flashcard, Challenge, FlashcardChallenge
from django.contrib.messages import constants
from django.contrib import messages

def create_flashcard(request):
    if not request.user.is_authenticated:
        return redirect('/users/login')
    if request.method == 'GET':
        categories = Category.objects.all()
        difficulties = Flashcard.DIFFICULTY_CHOICES
        flashcards = Flashcard.objects.filter(user=request.user)
        
        category_filter = request.GET.get('category')
        difficulty_filter = request.GET.get('difficulty')

        if category_filter:
            flashcards = flashcards.filter(category__id = category_filter)

        if difficulty_filter:
            flashcards = flashcards.filter(difficulty = difficulty_filter )

        return render(request, 'create_flashcard.html', {'categories': categories, 'difficulties': difficulties, 'flashcards': flashcards})
    
    elif request.method == 'POST':
        question = request.POST.get('question')
        answer = request.POST.get('answer')
        category = request.POST.get('category')
        difficulty = request.POST.get('difficulty')

        if len(question.strip()) == 0 or len(answer.strip()) == 0:
            messages.add_message(request, constants.ERROR, 'Preencha os campos de pergunta e resposta')
            return redirect('/flashcards/create_flashcard')

        flashcard = Flashcard(
            user = request.user,
            question = question,
            answer = answer,
            category_id = category,
            difficulty = difficulty,
        )

        flashcard.save()

        messages.add_message(request, constants.SUCCESS, 'Flashcard criado com sucesso')
        return redirect('/flashcards/create_flashcard')

def delete_flashcard(request, id):

    if not request.user.is_authenticated:
        return redirect('/users/login')
    
    flashcard = Flashcard.objects.get(id=id)
    if(request.user == flashcard.user):
        flashcard.delete()
        messages.add_message(request, constants.SUCCESS, 'Flashcard deletada com sucesso')
        return redirect('/flashcards/create_flashcard/')
    else:
        messages.add_message(request, constants.ERROR, 'Acesso negado para deletar o flashcard')
        return redirect('/flashcards/create_flashcard/')
    
def create_challenge(request):
    if not request.user.is_authenticated:
        return redirect('/users/login')
    
    if request.method == 'GET':
        categories = Category.objects.all()
        difficulties = Flashcard.DIFFICULTY_CHOICES
        return render(request, 'create_challenge.html', {'categories': categories, 'difficulties': difficulties})
    
    elif request.method == 'POST':
        title = request.POST.get('title')
        categories = request.POST.get('category')
        difficulty = request.POST.get('difficulty')
        number_questions = request.POST.get('number_questions')

        if len(title.strip()) == 0:
            messages.add_message(request, constants.ERROR, 'Escolha um título para o desafio')
            return redirect('/flashcards/create_challenge/')
        if categories is None:
            messages.add_message(request, constants.ERROR, 'Escolha ao menos uma categoria')
            return redirect('/flashcards/create_challenge/')
        if not number_questions or int(number_questions) <= 0:
            messages.add_message(request, constants.ERROR, 'Escolha um número de perguntas maior do que 0')
            return redirect('/flashcards/create_challenge/')

        flashcards = Flashcard.objects.filter(user=request.user).filter(difficulty=difficulty).filter(category_id__in=categories).order_by('?')
        
        if flashcards.count() < int(number_questions):
            messages.add_message(request, constants.ERROR, 'Nessa categoria e dificuldade há ' + str(flashcards.count()) + ' flascard(s) disponível(is)')
            return redirect('/flashcards/create_challenge/')

        challenge = Challenge(
            user = request.user,
            title = title,
            number_questions = number_questions,
            difficulty = difficulty
        )
        challenge.save()
        challenge.category.add(*categories)
        
        flashcards = flashcards[: int(number_questions)]

        for flashcard in flashcards:
            flashcard_challenge = FlashcardChallenge(
                flashcard = flashcard,
            )
            flashcard_challenge.save()
            challenge.flashcards.add(flashcard_challenge)

        challenge.save()

        return redirect('/flashcards/index_challenges/')
    
def index_challenges(request):
    if not request.user.is_authenticated:
        return redirect('/users/login')

    challenges = Challenge.objects.filter(user=request.user)
    categories = Category.objects.all()
    difficulties = Flashcard.DIFFICULTY_CHOICES

    category_filter = request.GET.get('category')
    difficulty_filter = request.GET.get('difficulty')

    if category_filter:
        challenges = challenges.filter(category__id = category_filter)

    if difficulty_filter:
        challenges = challenges.filter(difficulty = difficulty_filter )

    # TODO: desenvolver status

    return render(request, 'index_challenges.html', {'challenges': challenges,'categories': categories, 'difficulties': difficulties})

def challenge(request, id):
    if not request.user.is_authenticated:
        return redirect('/users/login')

    challenge = Challenge.objects.get(id=id)
    if not challenge.user == request.user:
        raise Http404()

    if request.method == 'GET':
        successes = challenge.flashcards.filter(answered=True).filter(flashcard_success=True).count()
        errors  = challenge.flashcards.filter(answered=True).filter(flashcard_success=False).count()
        missing = challenge.flashcards.filter(answered=False).count()

        return render(request,'challenge.html', {'challenge': challenge, 'successes': successes, 'errors': errors, 'missing': missing})
    
def answer_flashcard(request, id):
    if not request.user.is_authenticated:
        return redirect('/users/login')

    flashcard_challenge = FlashcardChallenge.objects.get(id=id)
    flashcard_success = request.GET.get('flashcard_success')
    challenge_id = request.GET.get('challenge_id')

    if not flashcard_challenge.flashcard.user == request.user:
        raise Http404()

    flashcard_challenge.answered = True
    flashcard_challenge.flashcard_success = True if flashcard_success == '1' else False
    flashcard_challenge.save()
    return redirect(f'/flashcards/challenge/{challenge_id}/')

def report(request, id):
    challenge = Challenge.objects.get(id=id)

    successes = challenge.flashcards.filter(flashcard_success=True).count()
    errors = challenge.flashcards.filter(flashcard_success=False).count()

    data = [successes, errors]

    categories = challenge.category.all()
    category_names = [category.name for category in categories]

    data2 = []
    for category in categories:
        data2.append(challenge.flashcards.filter(flashcard__category=category).filter(flashcard_success=True).count())

    return render(request, 'report.html', {'challenge': challenge, 'data': data, 'categories': category_names, 'data2': data2})

flashcards/templates/challenge.html
{% extends "main.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/index_challenges.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_challenge.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}

    {% include 'partials/header.html' %}

    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <h3 class="font-secondary" >Desafio iniciado</h3>
                <span class="badge-category">Programação</span>
                <span class="badge-category" >Matemática</span>
                <br>
                <br>
                <br>
                {% for flashcard in challenge.flashcards.all %}
                    <div class="box-new-flashcard {% if flash.respondido %}op2{% endif %}">
                        <div class="flashcard {{flashcard.flashcard.css_difficulty}}">
                            <div class="flashcard-category">
                                {{flashcard.flashcard.category}}
                            </div>
                            <br>
                            <br>
                            <div class="flashcard-box-item" onclick="flip_card( {{flashcard.id}} )">
                                <p class="flashcard-item">{{flashcard.flashcard.question}}</p>
                            </div>

                            {% if not flashcard.answered %}
                                <div class="answer">
                                    <a href="{% url 'answer_flashcard' flashcard.id %}?flashcard_success=0&challenge_id={{challenge.id}}"><i class='bx bxs-x-square icon-red'></i></a>
                                    <a href="{% url 'answer_flashcard' flashcard.id %}?flashcard_success=1&challenge_id={{challenge.id}}"><i class='bx bxs-check-square icon-green' ></i></a>
                                </div>  
                            {% else %} 
                                {% if flashcard.flashcard_success %}
                                    <span class="badge bg-success">Acertou</span>
                                {% else %}
                                    <span class="badge bg-danger">Errou</span>
                                {% endif%}
                            {% endif %}
                        </div>
                        <div class="answer-flashcard" id="{{flashcard.id}}">
                            {{flashcard.flashcard.answer}}
                        </div>
                    </div>
                    <br>
                    <br>
                {% endfor %}

            </div>
            <div class="col-md">

                <h3 class="font-secondary">Resultado</h3>
                <p class="font-p">Acertos: {{successes}}</p>
                <p class="font-p">Erros: {{errors}}</p>
                <p class="font-p">Faltantes: {{missing}}</p>
                <br>
                <a class="btn-register btn-challenge" href="{% url 'report' challenge.id %}">Relatório detalhado</a>
            </div>
        </div>

    </div>
    <script src="{% static 'flashcards/js/flashcard.js' %}"></script>
{% endblock 'content' %}

flashcards/templates/create_challenge.html
{% extends "main.html" %}
{% load static %}
{% block 'header' %}
    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_challenge.css' %}" rel="stylesheet">
{% endblock 'header' %}
{% block 'content' %}

    {% include 'partials/header.html' %}

    <div class="container ctx">
        <br>
        <br>
        <h2 class="font-main">Iniciar desafio</h2>
        <p class="fonte-secondary">Escolha as categorias e a dificuldade do desafio</p>
        {% if messages %}
            <br>
            {% for message in messages %}
                <section class="alert {{message.tags}}">
            {{message}}
                </section>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-md">
                <form action="{% url 'create_challenge' %}" method="POST">{% csrf_token%}
                <label for="">Título</label>
                <input type="text" class="form-control" name="title">
            </div>
            <div class="col-md">
                <label>Categoria</label>
                <select name="category" class="form-select" multiple>
                    {% for category in categories %}
                        <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <label>Dificuldade</label>
                <select name="difficulty" class="form-select">
                    {% for difficulty in difficulties %}
                        <option value="{{difficulty.0}}">{{difficulty.1}}</option>
                    {% endfor %}
            </select>
            </div>
            <div class="col-md">
                <label>Quantidade de perguntas</label>
                <input type="number" class="form-control" name="number_questions">
            </div>
        </div>
        <br>
        <br>
        <input type="submit" class="btn-register" value="Iniciar desafio">
        </form>
    </div>
{% endblock 'content' %}

flashcards/templates/create_flashcard.html
{% extends "main.html" %}
{% load static %}
{% block 'header' %}
    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_flashcard.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% endblock 'header' %}
{% block 'content' %}
    {% include 'partials/header.html' %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <div class="box-form">
                    <form action="{% url 'create_flashcard' %}" method="POST"> {% csrf_token %}
                        <h3>Novo flashcard</h3>
                        {% if messages %}
                            <br>
                            {% for message in messages %}
                                <section class="alert {{message.tags}}">
                            {{message}}
                                </section>
                            {% endfor %}
                        {% endif %}
                        <br>
                        <label>Pergunta</label>
                        <input type="text" class="form-control" name="question">
                        <br>
                        <label>Resposta</label>
                        <textarea class="form-control" name="answer"></textarea>
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <label for="">Categoria</label>
                                <select class="form-select" name="category">
                                    {% for category in categories %}
                                        <option value="{{category.id}}">{{category}}</option>
                                    {% endfor%}
                                </select>
                            </div>
                            <div class="col-md">
                                <label for="">Dificuldade</label>
                                <select class="form-select" name="difficulty">
                                    {% for difficulty in difficulties %}
                                        <option value="{{difficulty.0}}">{{difficulty.1}}</option>
                                    {% endfor%}
                                </select>
                            </div>
                        </div>
                        <br>
                        <input type="submit" value="Enviar" class="btn-register">
                        <br>
                        <br>
                    </form>
                </div>
            </div>
            <div class="col-md">
                <form action="{% url 'create_flashcard' %}" method="GET">
                    <div class="row">
                        <div class="col-md">
                            <label for="">Categoria</label>
                            <select name="category" id="" class="form-select">
                                <option value="">Todas as categorias</option>
                                {% for category in categories %}
                                    <option value="{{category.id}}">{{category}}</option>
                                {% endfor%}
                            </select>
                        </div>
                        <div class="col-md">
                            <label for="">Dificuldade</label>
                            <select name="difficulty" id="" class="form-select">
                                <option value="">Todas as dificuldades</option>
                                {% for difficulty in difficulties %}
                                    <option value="{{difficulty.0}}">{{difficulty.1}}</option>
                                {% endfor%}
                            </select>
                        </div>
                        <div class="col-md">
                            <br>
                            <input type="submit" style="width: 100%" value="Filtrar" class="btn-register">
                        </div>
                    </div>
                </form>
                <br>
                <br>
                {% for flashcard in flashcards %}
                    <div class="box-new-flashcard" onclick="flip_card( {{flashcard.id}} )">
                        <div class="flashcard ">
                            <div class="flashcard-category">
                                {{flashcard.category}}
                            </div>
                            <a href="{% url 'delete_flashcard' flashcard.id %}"><i class='icon-exit bx bx-x-circle'></i></a>
                            <br>
                            <br>
                            <div class="flashcard-box-item">
                                <p class="flashcard-item">{{flashcard.question}}</p>
                            </div>
                        </div>
                        <div class="answer-flashcard" id="{{flashcard.id}}">
                            {{flashcard.answer}}
                        </div>
                    </div>
                <br>
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'flashcards/js/flashcard.js' %}"></script>
{% endblock 'content' %}

flashcards/templates/index_challenges.html
{% extends "main.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_challenge.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/index_challenges.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}

    {% include 'partials/header.html' %}

    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <form action="{% url 'index_challenges' %}" method="GET">
                    <label for="">Categoria</label>
                    <select name="category" id="" class="form-select">
                        <option value="">Todas as categorias</option>
                        {% for category in categories %}
                            <option value="{{category.id}}">{{category}}</option>
                        {% endfor%}
                    </select>
            </div>
            <div class="col-md">
                <label for="">Dificuldade</label>
                <select name="difficulty" id="" class="form-select">
                    <option value="">Todas as dificuldades</option>
                    {% for difficulty in difficulties %}
                        <option value="{{difficulty.0}}">{{difficulty.1}}</option>
                    {% endfor%}
                </select>
            </div>
            <div class="col-md">
                <br>
                <input type="submit" value="Filtrar" class="btn-register">
                </form>
            </div>
        </div>
        <br>
        <br>
        <div class="box-list">
            <table>
                <thead>
                  <tr>
                    <th scope="col">Desafio</th>
                    <th scope="col">Título</th>
                    <th scope="col">Dificuldade</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                    {% for challenge in challenges %}
                        <tr class="line">
                            <th><a href="{% url 'challenge' challenge.id %}">{{challenge.id}}</a></th>
                            <td>{{challenge.title}}</td>
                            <td>{{challenge.get_difficulty_display}}</td>
                            <td>{{challenge.status}}</td>
                        </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    <script src="{% static 'flashcard/js/flashcard.js' %}"></script>
{% endblock 'content' %}

flashcards/templates/report.html
{% extends "main.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/create_challenge.css' %}" rel="stylesheet">
    <link href="{% static 'flashcards/css/index_challenges.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <p class="font-secondary">{{challenge.title}}</p>
                <hr>
                <canvas id="graphic1"></canvas>
            </div>
            <div class="col-md">
                <br>
                <br>
                <br>
                <br>
                <div style="background-color: white;">
                    <canvas id="graphic2"></canvas>
                </div>
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
      const context = document.getElementById('graphic1');
    
      new Chart(context, {
        type: 'pie',
        data: {
          labels: ['Acertos', 'Erros'],
          datasets: [{
            label: 'Quantidade',
            data: {{data}},
            borderWidth: 1
          }]
        },
        
      });
    </script>

    <script>
      const context2 = document.getElementById('graphic2');
    
      new Chart(context2, {
        type: 'radar',
        data: {
          labels: {{categories|safe}},
          datasets: [{
            label: 'Quantidade de acertos',
            data: {{data2}},
            borderWidth: 1,
            fill: true,
            backgroundColor: 'rgba(255, 99, 132, 0.2)',
            borderColor: 'rgb(255, 99, 132)',
            pointBackgroundColor: 'rgb(255, 99, 132)',
            pointBorderColor: '#fff',
            pointHoverBackgroundColor: '#fff',
            pointHoverBorderColor: 'rgb(255, 99, 132)'
          }]
        },
        
      });
    </script>
{% endblock 'content' %}